# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 11:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VkConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=50)),
                ('_token', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VkPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', django.contrib.postgres.fields.jsonb.JSONField()),
                ('_date', models.IntegerField()),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('reposts', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('owner_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkontakte.VkGroup')),
            ],
        ),
        migrations.CreateModel(
            name='VkUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sex', models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Woman'), (2, 'Man')])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('_bdate', models.CharField(max_length=20)),
                ('bdate', models.DateField()),
                ('university', models.IntegerField(default=0)),
                ('graduation', models.IntegerField(default=0)),
                ('twitter', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='vkpost',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkontakte.VkUser'),
        ),
        migrations.AddField(
            model_name='vkpost',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkontakte.VkPost'),
        ),
        migrations.AddField(
            model_name='vkgroup',
            name='users',
            field=models.ManyToManyField(related_name='groups', to='vkontakte.VkUser'),
        ),
    ]
