# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkontakte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='_bdate',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='bdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='twitter',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
