# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkontakte', '0002_auto_20170404_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='faculty',
            field=models.IntegerField(default=0),
        ),
    ]
