# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkontakte', '0005_auto_20170404_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkpost',
            name='owner_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vkontakte.VkGroup'),
        ),
        migrations.AlterField(
            model_name='vkpost',
            name='owner_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vkontakte.VkUser'),
        ),
    ]
