# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vkontakte', '0007_auto_20170404_0843'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vkpost',
            unique_together=set([('id', 'owner_user')]),
        ),
    ]
