# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkontakte', '0009_vkpost_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkpost',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
