# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vkontakte', '0010_auto_20170405_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vkpost',
            name='date',
        ),
    ]
