# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkontakte', '0012_auto_20170405_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vkuser',
            name='_bdate',
        ),
        migrations.RemoveField(
            model_name='vkuser',
            name='bdate',
        ),
        migrations.RemoveField(
            model_name='vkuser',
            name='twitter',
        ),
        migrations.AddField(
            model_name='vkuser',
            name='day',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='vkuser',
            name='month',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='vkuser',
            name='year',
            field=models.IntegerField(default=-1),
        ),
    ]
