# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkontakte', '0013_auto_20170419_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='day',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='month',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='year',
            field=models.IntegerField(default=None),
        ),
    ]
