# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkontakte', '0009_vkpost_post_id'),
        ('lemmatize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemmameet',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lemma_meets', to='vkontakte.VkPost'),
            preserve_default=False,
        ),
    ]
