# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatize', '0003_auto_20170405_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
