# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatize', '0004_auto_20170405_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='source',
            field=models.CharField(default='REQUIERD', max_length=100),
            preserve_default=False,
        ),
    ]
