# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatize', '0006_auto_20170421_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lemmameet',
            name='source',
        ),
    ]
