# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_nsu', '0002_auto_20170419_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynsuuser',
            name='course',
            field=models.CharField(max_length=100),
        ),
    ]
