# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_nsu', '0003_auto_20170419_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynsuuser',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mynsuuser',
            name='faculty',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mynsuuser',
            name='group',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mynsuuser',
            name='qualification',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='mynsuuser',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Woman'), (2, 'Man')], null=True),
        ),
        migrations.AlterField(
            model_name='mynsuuser',
            name='user_type',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
