# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkontakte', '0015_auto_20170419_1750'),
        ('my_nsu', '0005_auto_20170420_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynsuuser',
            name='vk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_nsu_user', to='vkontakte.VkUser'),
        ),
    ]
